apiVersion: v1
kind: Service
metadata:
  name: ins-generic-backend-preprod
  labels:
    app: genericbackend
spec:
  type: ClusterIP
  selector:
    app: genericbackend
    tier: ins6
  ports:
  - port: 5003
    targetPort: 5000
