apiVersion: v1
kind: Service
metadata:
  name: ins-employer-backend-preprod
  labels:
    app: employerbackend
spec:
  type: ClusterIP
  selector:
    app: employerbackend
    tier: ins2
  ports:
  - port: 5001
    targetPort: 5000
