apiVersion: v1
kind: Service
metadata:
  name: ins-ums-backend-preprod
  labels:
    app: umsbackend
spec:
  type: ClusterIP
  selector:
    app: umsbackend
    tier: ins
  ports:
  - port: 5000
    targetPort: 5000
