apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: ins-infra-backend-prod
  name: ins-infra-backend-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ins-infra-backend-prod
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: ins-infra-backend-prod
    spec:
      containers:
        - image: gcr.io/inscholaris-303015/ins-infra-backend-prod:latest
          name: ins-infra-backend-prod
          ports:
            - containerPort: 9082
          resources: {}
      restartPolicy: Always
status: {}

