apiVersion: v1
kind: Service
metadata:
  name: ins-search-backend-preprod
  labels:
    app: searchbackend
spec:
  type: ClusterIP
  selector:
    app: searchbackend
    tier: ins4
  ports:
  - port: 9085
    targetPort: 9085

