apiVersion: v1
kind: Service
metadata:
  name: ins-infra-backend-preprod
  labels:
    app: infrabackend
spec:
  type: ClusterIP
  selector:
    app: infrabackend
    tier: ins3
  ports:
  - port: 9082
    targetPort: 9082

